// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        {
          Strategies: [
            { type: 'autogenerated', dirName: 'reference/strategy' },
          ],
        },
        {
          Decisions: [
            { type: 'autogenerated', dirName: 'reference/decisions' },
          ],
        },
        {
          Projects: [{ type: 'autogenerated', dirName: 'reference/projects' }],
        },
      ],
    },
  ],
};

module.exports = sidebars;
