name: Build app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build app
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - name: Install Tuist
      run: |
        bash <(curl -Ls https://install.tuist.io)
    - name: Build app
      run: |
        tuist build App
