name: CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 4 * * 2'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        # https://aka.ms/codeql-docs/language-support
        language:
          - javascript
          - typescript

    steps:
    - uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

