name: Build website

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/website-review.yml'
      - 'website/**'

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache-dependency-path: website/yarn.lock
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
